# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: KF SDK Build

on:
  release:
    types: [created]
  # pull_request:
  #   types: [opened, closed]
  # push:
  #   branches:    
  #     - 'beta'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
  
      - name: setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies=false]

      - name: git config
        run: |
          git config --global user.email "saravanan.10393@gmail.com"
          git config --global user.name "sara"
            
      - name: Run build
        run:  pnpm run build

      - name: pump package version
        run:  pnpm version patch

      - name: Publish package to npm
        run:  pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
